# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PagoCIF
                                 A QGIS plugin
 Plugin que calcula el pago del beneficio CIF 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-11
        copyright            : (C) 2024 by Belky Alfonso , Enrique Blanco, Universidad Distrital Francisco Jose de Caldas
        email                : byalfonsoc@udistrital.edu.co y eblancob@udistrital.edu.co 
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PagoCIF class from file PagoCIF.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Pago_CIF import PagoCIF
    return PagoCIF(iface)
