# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PagoCIFDialog
                                 A QGIS plugin
 Plugin que calcula el pago del beneficio CIF 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-11
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Belky Alfonso , Enrique Blanco, Universidad Distrital Francisco Jose de Caldas
        email                : byalfonsoc@udistrital.edu.co y eblancob@udistrital.edu.co 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .Pago_CIF import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Pago_CIF_dialog_base.ui'))


class PagoCIFDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, Modulo, parent=None):
        """Constructor."""
        super(PagoCIFDialog, self).__init__(parent)
        self.rutaBase = Modulo.rutaBase
        self.divipola = Modulo.divipola
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.cBDepartamento.currentIndexChanged.connect(lambda: Modulo.llenarlistamupios())
        self.cBMunicipio.currentIndexChanged.connect(lambda: Modulo.validarmpio())
        self.cBMunicipio.currentIndexChanged.connect(lambda: Modulo.cargarlistaespecies())
        self.pBCalcular.clicked.connect(lambda: Modulo.calcularresultado())
        self.pBLimpiar.clicked.connect(lambda: Modulo.limpiarformulario())
        self.pBAyuda.clicked.connect(lambda: Modulo.abrirayuda())

    


